import type { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';

import Container from '../components/Container';
import Navigation from '../components/Navigation';
import Home from '../components/Section/Home';
import About from '../components/Section/About';
import Project from '../components/Section/Project';
import Blog from '../components/Section/Blog';
import Contact from '../components/Section/Contact';

interface Post {
  slug: string;
  title: string;
  tags: string[];
  image: string;
  excerpt: string;
  date: string;
  isFeatured: boolean;
}

interface Props {
  posts: Post[];
}

const HomePage = ({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Web Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Navigation />

        <Home />
        <About />
        <Project />
        <Blog />
        <Contact />
      </Container>
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  let posts: Post[] = [];

  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_BLOG_API}/posts/featured`
    );

    posts = await response.json();
  } catch (err) {
    return {
      props: { posts: [] },
    };
  }

  return {
    props: { posts },
  };
};

export default HomePage;
